/**
 * Canonical application error codes for WaveShift Nexus.
 * Adheres directly to HackIllinois Adonix API error standardization.
 */
export enum ErrorCode {
  // Client Errors (400)
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MALFORMED_TOKEN = 'MALFORMED_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  REPLAY_ATTACK_DETECTED = 'REPLAY_ATTACK_DETECTED',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',

  // Authentication & Authorization (401, 403)
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',

  // Not Found (404)
  SHIFT_NOT_FOUND = 'SHIFT_NOT_FOUND',
  VOLUNTEER_NOT_FOUND = 'VOLUNTEER_NOT_FOUND',
  REGISTRATION_NOT_FOUND = 'REGISTRATION_NOT_FOUND',
  SWAP_NOT_FOUND = 'SWAP_NOT_FOUND',

  // Conflict & Concurrency (409)
  SCHEDULE_CONFLICT = 'SCHEDULE_CONFLICT',
  SCHEDULE_BUFFER_CONFLICT = 'SCHEDULE_BUFFER_CONFLICT',
  DAILY_FATIGUE_EXCEEDED = 'DAILY_FATIGUE_EXCEEDED',
  MISSING_SKILL_CERTIFICATION = 'MISSING_SKILL_CERTIFICATION',
  ALREADY_REGISTERED = 'ALREADY_REGISTERED',
  SHIFT_FULL = 'SHIFT_FULL',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  CONCURRENT_MUTATION_IN_PROGRESS = 'CONCURRENT_MUTATION_IN_PROGRESS',
  SWAP_INVALID = 'SWAP_INVALID',
  SWAP_CONFLICT = 'SWAP_CONFLICT',

  // Server & Database Errors (500)
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
}
